### ISSUE TITLE
代码中计算gps与上一帧时间差好像缺少绝对值

### ISSUE THREAD

**Issue by liujm2001** [LIAS-CUHKSZ/liv_syn#1]
您好，感谢您开源的时间同步方法！
在对照代码学习的时候我发现一个问题，请问 src/mvs_ros_pkg/src/grab_trigger.cpp 的420行是否需要加一个abs呢？
期待您的回复！

**Comment by NeoZng** [comment]
是的，全部都需要绝对值，之前推送的是尚未完善的代码，在更新中已经解决。
