### ISSUE TITLE
相机同步配置文件问题

### ISSUE THREAD

**Issue by MisEty** [LIAS-CUHKSZ/liv_syn#2]
您好，我注意到您的代码中从配置文件中读取了一系列参数来设置相机工作模式
```   
    int ExposureAuto = Params["ExposureAuto"];
    int ExposureTimeLower = Params["AutoExposureTimeLower"];
    int ExposureTimeUpper = Params["AutoExposureTimeUpper"];
    int ExposureTime = Params["ExposureTime"];
    int ExposureAutoMode = Params["ExposureAutoMode"];
    int GainAuto = Params["GainAuto"];
    float Gain = Params["Gain"];
    float Gamma = Params["Gamma"];
    int GammaSlector = Params["GammaSelector"];
    int CenterAlign = Params["CenterAlign"];
```
但是其中有些参数存在问题，比如ExposureAutoMode和ExposureAuto似乎是重复的，并且ExposureAutoMode在配置文件中被注释了。而CenterAlign似乎并没有被使用。

**Comment by MisEty** [comment]
还有个问题就是在LIV-handhold项目中似乎并没有将图像时间和GPS时间进行匹配计算，而是直接将共享内存中的时间戳赋给相机。
https://github.com/sheng00125/LIV_handhold/blob/e6dde33f81c5e7272c4088e9a844f5ac6a5b3632/mvs_ros_pkg/src/grab_trigger.cpp#L20

```
       int64_t b = pointt->low;
      // printf("b:%d\n");
      double time_pc = b / 1000000000.0;
      ros::Time rcv_time = **ros::Time(time_pc);**
```

**Comment by CXT-666** [comment]
> 还有个问题就是在LIV-handhold项目中似乎并没有将图像时间和GPS时间进行匹配计算，而是直接将共享内存中的时间戳赋给相机。 https://github.com/sheng00125/LIV_handhold/blob/e6dde33f81c5e7272c4088e9a844f5ac6a5b3632/mvs_ros_pkg/src/grab_trigger.cpp#L20
> 
> ```
>        int64_t b = pointt->low;
>       // printf("b:%d\n");
>       double time_pc = b / 1000000000.0;
>       ros::Time rcv_time = **ros::Time(time_pc);**
> ```

您好，我最近需要做雷达和相机硬同步。在这个项目和LIV_handhold都看到了你，可以交流以下吗

**Comment by NeoZng** [comment]
LIV_handhold中的方法是不完善的，并不是真正的硬件触发，它使用获取到的最新雷达包中的时间赋给相机，误差预计在~50ms级。若相机发生丢帧会出现更严重的时间错配。

**Comment by NeoZng** [comment]
> 您好，我注意到您的代码中从配置文件中读取了一系列参数来设置相机工作模式
> 
> ```
>     int ExposureAuto = Params["ExposureAuto"];
>     int ExposureTimeLower = Params["AutoExposureTimeLower"];
>     int ExposureTimeUpper = Params["AutoExposureTimeUpper"];
>     int ExposureTime = Params["ExposureTime"];
>     int ExposureAutoMode = Params["ExposureAutoMode"];
>     int GainAuto = Params["GainAuto"];
>     float Gain = Params["Gain"];
>     float Gamma = Params["Gamma"];
>     int GammaSlector = Params["GammaSelector"];
>     int CenterAlign = Params["CenterAlign"];
> ```
> 
> 但是其中有些参数存在问题，比如ExposureAutoMode和ExposureAuto似乎是重复的，并且ExposureAutoMode在配置文件中被注释了。而CenterAlign似乎并没有被使用。

该相机ros包直接使用了开源实现，若有需要可以自行修改😊

**Comment by xuankuzcr** [comment]
> LIV_handhold中的方法是不完善的，并不是真正的硬件触发，它使用获取到的最新雷达包中的时间赋给相机，误差预计在~50ms级。若相机发生丢帧会出现更严重的时间错配。

由于PPS信号给了LiDAR，同时GPRMC的时间戳通过SDK提供，从而保证了相机和LiDAR在同一时刻触发（采用Livox同步机制）@NeoZng。因此，我们将LiDAR的时间戳通过共享内存赋值给相机帧。另外，LiDAR帧头时间戳是synthetic的GPS时间戳，因此相机和LiDAR获取的都是GPRMC中的时间戳@MisEty。整套方案的同步精度排除无法控制的曝光时间在ns级别@NeoZng ，至于CenterAlign是我们考虑了曝光延时的同步方案，还未开源，因此从代码中删掉了@MisEty。如果有其他问题可以在LIV_handheld下提issue，每个issue我都会回@CXT-666。**ps: 建议repo作者在README中引用LIV_handheld仓库。**

**Comment by NeoZng** [comment]
> > LIV_handhold中的方法是不完善的，并不是真正的硬件触发，它使用获取到的最新雷达包中的时间赋给相机，误差预计在~50ms级。若相机发生丢帧会出现更严重的时间错配。
> 
> 由于PPS信号给了LiDAR，同时GPRMC的时间戳通过SDK提供，从而保证了相机和LiDAR在同一时刻触发（采用Livox同步机制）@NeoZng。因此，我们将LiDAR的时间戳通过共享内存赋值给相机帧。另外，LiDAR帧头时间戳是synthetic的GPS时间戳，因此相机和LiDAR获取的都是GPRMC中的时间戳@MisEty。整套方案的同步精度排除无法控制的曝光时间在ns级别@NeoZng ，至于CenterAlign是我们考虑了曝光延时的同步方案，还未开源，因此从代码中删掉了@MisEty。如果有其他问题可以在LIV_handheld下提issue，每个issue我都会回@CXT-666。**ps: 建议repo作者在README中引用LIV_handheld仓库。**

添加了引用😊。虽然雷达数据频率被设置为10Hz，但是无法保证每次发来的第一个数据包时间恰好在0.1s的间隙，激光雷达数据的采集是连续的。另外，个人认为您的方案主要的问题在于没有考虑雷达和相机采集出现丢帧的情况。

**Comment by xuankuzcr** [comment]
感谢回复。刚才你讨论的是有两个问题，一个是说有延迟，一个是丢帧时有时间匹配错误。前者你完全理解错了，我已经说明了。后者在正常情况下，不会丢帧，因为曝光时间（主要时间）+ 线路延迟 + cmos响应时间 + 其他延时不可能超过100ms。如果曝光时间过大超过20ms，这个图像数据会运动模糊的特别严重，无法使用。如果是线路延迟时间过大，即数据带宽或者接口松动造成的丢帧问题，确实会时间戳赋错帧。但我们并不是在做商业化，我们只提供能work的方案，不会考虑很多corner case。另外对于丢帧导致的时间戳赋错问题，如果真想解决的话两个if语句就能搞定。
